### ISSUE TITLE
Ratatui

### ISSUE THREAD

**Issue by joshka** [jzvolensky/weather-tui#1]
Hey there, I just saw this pop up in a notifications discord channel we have for [Ratatui](https://crates.io/crates/ratatui/). You might consider using Ratatui rather than tui-rs if you want to build on an actively maintained crate.

We're responsive to issues and PRs in our [Github Repo](https://github.com/ratatui-org/ratatui), and Discord / Matrix. Come say hi. 

There are more up to date docs and examples for Ratatui on [docs.rs](https://docs.rs/ratatui/latest/ratatui/) and a website with tutorials and other more in depth docs at https://ratatui.rs/.

**Comment by jzvolensky** [comment]
Thanks for letting me know! I didnt notice tui-rs is no longer maintained. Will switch over.
